//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Student_DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actor
    {
        public Actor()
        {
            this.MOVIEs = new HashSet<MOVIE>();
        }
    
        public string actor_Id { get; set; }
        public string actor_Fname { get; set; }
        public string actor_LName { get; set; }
        public string actor_gender { get; set; }
    
        public virtual ICollection<MOVIE> MOVIEs { get; set; }
    }
}
