//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Student_DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIE
    {
        public int MovieID { get; set; }
        public string actor_Id { get; set; }
        public string Movie_Name { get; set; }
        public string Movie_Year { get; set; }
    
        public virtual Actor Actor { get; set; }
    }
}
