//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Student_DBConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NCS2020Entities : DbContext
    {
        public NCS2020Entities()
            : base("name=NCS2020Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Actor> Actors { get; set; }
        public DbSet<AGENT> AGENTS { get; set; }
        public DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public DbSet<MOVIE> MOVIEs { get; set; }
        public DbSet<StudentsDept> StudentsDepts { get; set; }
        public DbSet<StudentsInfo> StudentsInfoes { get; set; }
    }
}
