//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Student_DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentsInfo
    {
        public string StdRegNumber { get; set; }
        public string StdName { get; set; }
        public Nullable<System.DateTime> StdDoBirth { get; set; }
        public Nullable<System.DateTime> StdRegDate { get; set; }
        public string StdContact { get; set; }
        public string StdEmail { get; set; }
        public Nullable<int> StdDeptCode { get; set; }
    }
}
